services:
  minio-server:
    image: docker.io/bitnami/minio:2024.1.29-debian-11-r0
    container_name: minio-server
    hostname: minio-server
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio@2020
      MINIO_DEFAULT_BUCKETS: data
      MINIO_SERVER_ACCESS_KEY: data_eng-acces-key
      MINIO_SERVER_SECRET_KEY: abc14fd97adb4e6f8d49b86c1e77b5fc
    volumes:
      - ./volumes/minio:/bitnami/minio/data:z
    ports:
      - '9000:9000'
      - '9001:9001'
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1G"
